name: Lint

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  lint:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py312
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py312
        continue-on-error: true
