name: Run Unit Test with Pytest

on: [push, pull_request, workflow_call]

jobs:
  test:
    name: Test via pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/default.txt -r requirements/test.txt
      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
